#pragma once
#include "helpers/cdelayer.hpp"
#define A_CONTROL_DELAY (5*1000)

#define A_TARGET_ROOM_TEMPERATURE 27.0
#define A_TARGET_ROOM_TEMPERATURE_STAGE0_GATE 0.5
#define A_TARGET_ROOM_TEMPERATURE_STAGE1_GATE 1.0
#define A_TARGET_ROOM_TEMPERATURE_STAGE0_HIGH (A_TARGET_ROOM_TEMPERATURE + A_TARGET_ROOM_TEMPERATURE_STAGE0_GATE)
#define A_TARGET_ROOM_TEMPERATURE_STAGE0_LOW  (A_TARGET_ROOM_TEMPERATURE - A_TARGET_ROOM_TEMPERATURE_STAGE0_GATE)
#define A_TARGET_ROOM_TEMPERATURE_STAGE1_HIGH (A_TARGET_ROOM_TEMPERATURE + A_TARGET_ROOM_TEMPERATURE_STAGE0_GATE + A_TARGET_ROOM_TEMPERATURE_STAGE1_GATE)
#define A_TARGET_ROOM_TEMPERATURE_STAGE1_LOW  (A_TARGET_ROOM_TEMPERATURE - A_TARGET_ROOM_TEMPERATURE_STAGE0_GATE - A_TARGET_ROOM_TEMPERATURE_STAGE1_GATE)

#define A_TARGET_ROOM_CO2 6000
#define A_TARGET_ROOM_ORGANIC 3000
#define A_TARGET_ROOM_MQ2 600

class CController : public helper::CDelayer
{
public:
  CController();
  ~CController();
  void check();
private:
  void controlExhaust();
  void controlRoomHeater();
  void controlRoomCooler();
};
